version: "2"
services:
  zookeeper:
    image: confluent/zookeeper:latest
    restart: always
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"

  kafka:
    hostname: kafka
    restart: always
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /tmp/docker/kafka1/logs:/logs
      - /tmp/docker/kafka1/data:/data
